### ISSUE TITLE
Module preambles and postambles seem to be lost

### ISSUE THREAD

**Issue by dbuenzli** [ocaml-doc/doc-ock#62]
Steps to reproduce:

```
opam switch 4.03.0
eval $(opam config env)
opam install fpath
odoc compile --output-dir /tmp/ --pkg fpath $(opam config var fpath:lib)/fpath.cmti
odoc html --output-dir /tmp/ /tmp/fpath.odoc
```

Now compare `/tmp/Fpath/index.html` with http://erratique.ch/software/fpath/doc/Fpath

**Comment by dbuenzli** [comment]
It seem preambles are not in. However stuff still gets lost. You can compare with 

```
opkg ocamldoc fpath
opkg odoc fpath 
opkg doc fpath 
opkg doc --odoc fpath
```

**Comment by lpw25** [comment]
I had a look at that file. The issue is that there is an unknown unicode character in the doc comment at line 655. Odoc sees this is an error but does not currently report these errors.

**Comment by dbuenzli** [comment]
Indeed thanks. I'll fix this but the tool should be robust with this. Report the error and replace the character with U+FFFD (`"\xEF\xBF\xBD"` in UTF-8 in OCaml).

**Comment by dbuenzli** [comment]
Note however that while there are *funny* characters on [that line](https://github.com/dbuenzli/fpath/blob/9cea8985f03d1d32762336e97fccf0f0fab8600a/src/fpath.mli#L655). The file is valid UTF-8 and the characters are not unknown. I think the issue must be rather be about handling text outside list elements in a list.

**Comment by trefis** [comment]
> I think the issue must be rather be about handling text outside list elements in a list.

I think that's correct.
I'll try to have a look at it "soon"
